version: '3.8'
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: onjo1479
      POSTGRES_DB: studyroom
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/studyroom
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: onjo1479
    depends_on:
      - db